### ISSUE TITLE
programmatically use

### ISSUE THREAD

**Issue by cooliobr** [futzu/umzz#10]
The 'umzz' can be used programmatically? In 'x9k3', I did it as follows.
```
#!/usr/bin/env pypy3
import subprocess
import x9k3

# Comando ffmpeg com a sa√≠da redirecionada para um pipe
ffmpeg_command = 'ffmpeg -hide_banner -nostats -v level+fatal  -hwaccel_device 0 -hwaccel qsv -i "udp://227.0.0.1:1234?overrun_nonfatal=1&fifo_size=288000&buffer_size=288000&timeout=90000000" -map 0 -c copy -f mpegts -'

# Inicie o processo ffmpeg
process = subprocess.Popen(ffmpeg_command, stdout=subprocess.PIPE, shell=True)

# Leia a sa√≠da do processo
input_stream = process.stdout

# Crie uma inst√¢ncia de X9K3
x9 = x9k3.X9K3(input_stream)

# Configure os outros argumentos
x9.args.output_dir = "/usr/share/ffplayout/public/live/scte35"
x9.args.sidecar_file = "/opt/mark/sidecar.txt"
x9.args.time = 4
x9.args.hls_tag = "x_scte35"
x9.args.live = True
##x9.args.delete = True
# Execute o X9K3
x9.run()

# Aguarde o processo ffmpeg terminar (opcional)
process.wait()
```

**Comment by futzu** [comment]
```smalltalk

import os
from m3ufu import M3uFu
from umzz.umzz import UMZZ 


m3u8 = "my_index.m3u8"
output_dir = "/home/me/output_dir"
sidecar_file = "/home/me/sidecar.txt"

fu = M3uFu()
fu.m3u8 = m3u8
if not os.path.isdir(output_dir):
    os.mkdir(output_dir)
try:
    fu.decode()
    um = UMZZ(fu.segments, output_dir, sidecar_file)
    um.go()
finally:
    return
```

I'm about to start working on this again, updates coming soon.

**Comment by cooliobr** [comment]
good morning Adrian, how can support you ? PayPal, bitcoin ??

**Comment by cooliobr** [comment]
how can I set Live and delete ? I new with python

**Comment by futzu** [comment]
Working off what we did before:
```smalltalk
import os
from m3ufu import M3uFu
from umzz.umzz import UMZZ 
from umzz.x9mp import X9MP

class MyUMZZ(UMZZ):                                                     #  <-------------- Subclass UMZZ  and over-ride  the  mp_run method

    def mp_run(self, pipe, manifest, dir_name):
        x9mp = X9MP()
        x9mp.sidecar_pipe = pipe
        x9mp.args.output_dir = dir_name                                      
        x9mp.args.live = True                                              # <------- Set live 
        x9mp.args.delete = True                                         # <------- Set delete
        try:
            x9mp.decode_m3u8(manifest=manifest.media)
        except Exception as err:
            print(err)
            print(manifest.media, "...........Failed")

m3u8 = "my_index.m3u8"
output_dir = "/home/me/output_dir"
sidecar_file = "/home/me/sidecar.txt"

fu = M3uFu()
fu.m3u8 = m3u8
if not os.path.isdir(output_dir):
    os.mkdir(output_dir)
try:
    fu.decode()
    um = MyUMZZ(fu.segments, output_dir, sidecar_file)      # < -------------- Use MyUMZZ instead of UMZZ
    um.go()
finally:
    return
```

**Comment by futzu** [comment]
You can set any of the command line args like that 
x9mp.args.input
x9mp.args.
x9mp.args.
x9mp.args.
x9mp.args.
x9mp.args.

**Comment by cooliobr** [comment]
thanks bro, I new with python!

**Comment by futzu** [comment]
This is kind of weird too, it's not just the  python. I start up a separate sub process for each variant , but the main process is the one that parses the args so it has to pass everything in. I need to do this a better way.

**Comment by cooliobr** [comment]
do you know why the occurs "/usr/share/ffplayout/public/live/ch1/scte35_1/0/segment_21.ts:   start: 54.100000   end: 56.100000   duration: 2.000000
{'tags': {'#EXTINF': '2.000000,'}, 'name': '/usr/share/ffplayout/public/live/ch1/scte35_1/0/segment_17.ts', 'file': 'segment_17.ts', 'num': 17}
deleting /usr/share/ffplayout/public/live/ch1/scte35_1/0/segment_17.ts
throttling 1.86
/usr/share/ffplayout/public/live/ch1/scte35_1/0/segment_22.ts:   start: 56.100000   end: 58.100000   duration: 2.000000
{'tags': {'#EXTINF': '2.000000,'}, 'name': '/usr/share/ffplayout/public/live/ch1/scte35_1/0/segment_18.ts', 'file': 'segment_18.ts', 'num': 18}
deleting /usr/share/ffplayout/public/live/ch1/scte35_1/0/segment_18.ts
throttling 1.88
Process-1  is down
0 /DAhAAAAAAAAAP/wEAUAAAAJf78A/gApMuAACQAAAACD06tm
0 /DAhAAAAAAAAAP/wEAUAAAAJf78A/gApMuAACQAAAACD06tm
0 /DAhAAAAAAAAAP/wEAUAAAAJf78A/gApMuAACQAAAACD06tm
0 /DAhAAAAAAAAAP/wEAUAAAAJf78A/gApMuAACQAAAACD06tm
0 /DAhAAAAAAAAAP/wEAUAAAAJf78A/gApMuAACQAAAACD06tm


0 /DAhAAAAAAAAAP/wEAUAAAAJf78A/gApMuAACQAAAACD06tm
0 /DAhAAAAAAAAAP/wEAUAAAAJf78A/gApMuAACQAAAACD06tm
0 /DAhAAAAAAAAAP/wEAUAAAAJf78A/gApMuAACQAAAACD06tm
^CTraceback (most recent call last):"

**Comment by futzu** [comment]
Process 1 is down, means that one of variant processes either crashed or finished, which is not really all that helpful :)
I remember there was an issue with delete, but I don't remember what is was.  I was actively working on this a year ago, and then my mom fell and broke her hip, and then  died. I really got sidetracked with all that. 
##
That being said,
this project is now my focus as of today.
I am excited to get back to it, we will figure it out quickly. 
I have a significant update pushed to X9K3, which is umzz's parent class, 
I am checking the update  with umzz tonight.
Are you a UNIX guy? 
If so, I may give you a login to one of my servers and have you rsync the video up to me, so I test with it.

**Comment by futzu** [comment]
I just noticed you were doing a subprocess command, 

for style points do the import like this 

```smalltalk
from subprocess import Popen, PIPE
```
then call it like 
```smalltalk
process = Popen(ffmpeg_command, stdout=PIPE, stderr=PIPE, shell=True)
```
I got to check the syntax, but if you do stdout, and stderr  both to PIPE, there is way to write stdout to a var and stderr to var when you run it and , it makes it easier to read the output. Let me look it up.  
The reason for this is that stdout in the shell flushes more frequently than does stderr, that's true for anything running in a shell. Both ffmpeg and my stuff  both write to stdout and stderr.

**Comment by futzu** [comment]
This  is where genius **"is down"** message come, 
I use this to exit the variant process, I need add some better messages :)

```smalltalk 
    def is_running(self):
        """
        is_running checks to see if variant Processes are running
        """
        self.chk_sidecar()
        for v in self.variants:
            if v.is_alive():
                return True
            self.variants.pop(self.variants.index(v))
            print(v._name, " is down")        
        return False
```

**Comment by futzu** [comment]
I was thinking the wait() might be a problem.  We'll get on this tomorrow.

![image](https://github.com/futzu/umzz/assets/52701496/7025487c-90e6-494f-a98c-1774f1713f66)

**Comment by cooliobr** [comment]
now I on the road going to other state, I can return to test in one week!
but about variant, my stream has only one. my videos is only live, I can give you access to test

**Comment by futzu** [comment]
Yeah, send me a link man.

Here's a Popen.communicate() example

```smalltalk
from subprocess import Popen, PIPE


def run_cmd(cmd):
    p_out,p_err = Popen(cmd,stdout=PIPE,stderr=PIPE,shell =True).communicate()
    print(f'Command: {cmd}\n')
    print(f'Stdout:\n{p_out.decode()}\n')
    print(f'Stderr:\n{p_err.decode()}\n') 


if __name__ == '__main__':
    commands = ['ls -lah', "printf hey\n", 'find /home/a/ -name thesenuts', 'qbert']
    for cmd in commands:
        run_cmd(cmd)



```

**Comment by cooliobr** [comment]
hi brother, I going to my city today. I need talk with you about support in btc or PayPal.

**Comment by cooliobr** [comment]
Hi, my playout is 100% live channel http://200.194.238.229:8989/live/ch1/playlist.m3u8

**Comment by cooliobr** [comment]
i have tried now, I face with Process-1 is Down when in m3u8 have DISCONTINUITY, but this this continuity only appears when in playout change video file, there any way to bypass this ?

**Comment by futzu** [comment]
I want you upgrade umzz, 
`python3 -mpip install --upgrade umzz`

the version is 0.0.7
I want you to try the command line tool `umzz2`, I want to see if works as you need.
This is a rough draft, I'm going as fast as I can, I'm just super busy right now.
ignore the DeprecationWarning for now. 

```smalltalk
a@fu:~$ umzz2 -h
/home/a/.local/bin/umzz2:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').run_script('umzz==0.0.7', 'umzz2')

usage: umzz2 [-h] [-i INPUT] [-c] [-d] [-l] [-n] [-o OUTPUT_DIR] [-p] [-r]
             [-s SIDECAR_FILE] [-S] [-t TIME] [-T HLS_TAG] [-w WINDOW_SIZE] [-v]

optional arguments:
  -h, --help            show this help message and exit
  -i INPUT, --input INPUT
                        Input source, like /home/a/vid.ts or
                        udp://@235.35.3.5:3535 or https://futzu.com/xaa.ts or
                        https://example.com/not_a_master.m3u8 [default: stdin]

  -c, --continue_m3u8   Resume writing index.m3u8 [default:False]                               <--- NEW!

  -d, --delete          delete segments (enables --live) [default:False]

  -l, --live            Flag for a live event (enables sliding window m3u8)
                        [default:False]

  -n, --no_discontinuity
                        Flag to disable adding #EXT-X-DISCONTINUITY tags at splice                        <---- no discontinuity
                        points [default:False]

  -o OUTPUT_DIR, --output_dir OUTPUT_DIR
                        Directory for segments and index.m3u8 (created if needed)
                        [default:'.']

  -p, --program_date_time
                        Flag to add Program Date Time tags to index.m3u8 ( enables
                        --live) [default:False]

  -r, --replay          Flag for replay aka looping (enables --live,--delete)       <--- NEW!
                        [default:False]

  -s SIDECAR_FILE, --sidecar_file SIDECAR_FILE
                        Sidecar file of SCTE-35 (pts,cue) pairs.[default:None]

  -S, --shulga          Flag to enable Shulga iframe detection mode
                        [default:False]

  -t TIME, --time TIME  Segment time in seconds [default:2]

  -T HLS_TAG, --hls_tag HLS_TAG
                        x_scte35, x_cue, x_daterange, or x_splicepoint
                        [default:x_cue]

  -w WINDOW_SIZE, --window_size WINDOW_SIZE
                        sliding window size (enables --live) [default:5]

  -v, --version         Show version
```


programmatically it will work very similar .
I got to run out for a meeting, I'll be back later.

**Comment by cooliobr** [comment]
ok now

root@Hallo-Leo-e-Lully-192-168-234-53:~# umzz2 -h
usage: umzz2 [-h] [-i INPUT] [-c] [-d] [-l] [-n] [-o OUTPUT_DIR] [-p] [-r] [-s SIDECAR_FILE] [-S] [-t TIME] [-T HLS_TAG] [-w WINDOW_SIZE] [-v]

options:
  -h, --help            show this help message and exit
  -i INPUT, --input INPUT
                        Input source, like /home/a/vid.ts or udp://@235.35.3.5:3535 or https://futzu.com/xaa.ts or https://example.com/not_a_master.m3u8 [default: stdin]
  -c, --continue_m3u8   Resume writing index.m3u8 [default:False]
  -d, --delete          delete segments (enables --live) [default:False]
  -l, --live            Flag for a live event (enables sliding window m3u8) [default:False]
  -n, --no_discontinuity
                        Flag to disable adding #EXT-X-DISCONTINUITY tags at splice points [default:False]
  -o OUTPUT_DIR, --output_dir OUTPUT_DIR
                        Directory for segments and index.m3u8 (created if needed) [default:'.']
  -p, --program_date_time
                        Flag to add Program Date Time tags to index.m3u8 ( enables --live) [default:False]
  -r, --replay          Flag for replay aka looping (enables --live,--delete) [default:False]
  -s SIDECAR_FILE, --sidecar_file SIDECAR_FILE
                        Sidecar file of SCTE-35 (pts,cue) pairs.[default:None]
  -S, --shulga          Flag to enable Shulga iframe detection mode [default:False]
  -t TIME, --time TIME  Segment time in seconds [default:2]
  -T HLS_TAG, --hls_tag HLS_TAG
                        x_scte35, x_cue, x_daterange, or x_splicepoint [default:x_cue]
  -w WINDOW_SIZE, --window_size WINDOW_SIZE
                        sliding window size (enables --live) [default:5]
  -v, --version         Show version

**Comment by futzu** [comment]
I am having that kind of a day too man. :)

**Comment by futzu** [comment]
get v0.0.13, I just pushed it . You can just run **umzz**,  It should be working pretty well.
I'll do you a  programmatic example shortly.

**Comment by cooliobr** [comment]
> get v0.0.13, I just pushed it . You can just run **umzz**, It should be working pretty well.
> I'll do you a programmatic example shortly.

root@Hallo-Leo-e-Lully-192-168-234-53:~/tmp/umzz# pypy3 -mpip install .
Processing /root/tmp/umzz
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      Traceback (most recent call last):
        File "/usr/local/lib/pypy3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/local/lib/pypy3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/local/lib/pypy3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-gbcp3283/overlay/lib/pypy3.10/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-gbcp3283/overlay/lib/pypy3.10/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-gbcp3283/overlay/lib/pypy3.10/site-packages/setuptools/build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-gbcp3283/overlay/lib/pypy3.10/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 4, in <module>
        File "/root/tmp/umzz/umzz.py", line 14, in <module>
          from m3ufu import M3uFu
      ModuleNotFoundError: No module named 'm3ufu'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by cooliobr** [comment]
i will try on new server.

**Comment by futzu** [comment]
glad to see you using pypy3, pypy3 kicks ass. 

you forgot the `--upgrade`  


`pypy3 -mpip install --upgrade  umzz  `

if it still fails do 

`pypy3 -mpip install --upgrade  m3ufu umzz  `

v0.0.15 is the latest, everything should be working .

**Comment by cooliobr** [comment]
Using /root/.local/lib/pypy3.10/site-packages
Finished processing dependencies for umzz==0.0.15
root@Hallo-Leo-e-Lully-192-168-234-53:~/umzz# umzz2
Traceback (most recent call last):
  File "/usr/local/bin/umzz2", line 4, in <module>
    __import__('pkg_resources').run_script('umzz==0.0.15', 'umzz2')
  File "/root/.local/lib/pypy3.10/site-packages/pkg_resources/__init__.py", line 672, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/root/.local/lib/pypy3.10/site-packages/pkg_resources/__init__.py", line 1460, in run_script
    raise ResolutionError(
pkg_resources.ResolutionError: Script 'scripts/umzz2' not found in metadata at '/usr/local/lib/pypy3.10/site-packages/umzz-0.0.15.dist-info'
root@Hallo-Leo-e-Lully-192-168-234-53:~/umzz# umzz
Traceback (most recent call last):
  File "/usr/local/bin/umzz", line 4, in <module>
    __import__('pkg_resources').run_script('umzz==0.0.15', 'umzz')
  File "/root/.local/lib/pypy3.10/site-packages/pkg_resources/__init__.py", line 672, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/root/.local/lib/pypy3.10/site-packages/pkg_resources/__init__.py", line 1460, in run_script
    raise ResolutionError(
pkg_resources.ResolutionError: Script 'scripts/umzz' not found in metadata at '/usr/local/lib/pypy3.10/site-packages/umzz-0.0.15.dist-info'
root@Hallo-Leo-e-Lully-192-168-234-53:~/umzz#

**Comment by futzu** [comment]
I am not sure what's happen there.

Let me uninstall it and install it again to see what I get.

```js 
a@fu:~$ pypy3 -mpip uninstall  umzz --break-system-packages
Found existing installation: umzz 0.0.17
Uninstalling umzz-0.0.17:
  Would remove:
    /home/a/.local/bin/umzz
    /home/a/.local/bin/umzz2
    /home/a/.local/lib/pypy3.9/site-packages/umzz-0.0.17.dist-info/*
    /home/a/.local/lib/pypy3.9/site-packages/umzz.py
Proceed (Y/n)? y
  Successfully uninstalled umzz-0.0.17
a@fu:~$ pypy3 -mpip uninstall  m3ufu x9k3  --break-system-packages
Found existing installation: m3ufu 0.0.83
Uninstalling m3ufu-0.0.83:
  Would remove:
    /home/a/.local/bin/m3ufu
    /home/a/.local/lib/pypy3.9/site-packages/m3ufu-0.0.83.dist-info/*
    /home/a/.local/lib/pypy3.9/site-packages/m3ufu.py
Proceed (Y/n)? y
  Successfully uninstalled m3ufu-0.0.83
Found existing installation: x9k3 0.2.25
Uninstalling x9k3-0.2.25:
  Would remove:
    /home/a/.local/bin/x9k3
    /home/a/.local/lib/pypy3.9/site-packages/x9k3-0.2.25.dist-info/*
    /home/a/.local/lib/pypy3.9/site-packages/x9k3.py
Proceed (Y/n)? y
  Successfully uninstalled x9k3-0.2.25
a@fu:~$ 
```


Now, reinstall it. 
```js
a@fu:~$ pypy3 -mpip install --upgrade umzz --break-system-packages
Defaulting to user installation because normal site-packages is not writeable
Collecting umzz
  Obtaining dependency information for umzz from https://files.pythonhosted.org/packages/a3/50/a3ebd58de40c7e51a169858513003005895d8e7c31447f48232762b57391/umzz-0.0.17-py3-none-any.whl.metadata
  Using cached umzz-0.0.17-py3-none-any.whl.metadata (7.8 kB)
Requirement already satisfied: iframes>=0.0.7 in ./.local/lib/pypy3.9/site-packages (from umzz) (0.0.7)
Collecting m3ufu>=0.0.83 (from umzz)
  Obtaining dependency information for m3ufu>=0.0.83 from https://files.pythonhosted.org/packages/25/af/27acb7c4e7709f191686408b1acbb7a9b8a97c87b00fc5b9c83f735766f0/m3ufu-0.0.83-py3-none-any.whl.metadata
  Using cached m3ufu-0.0.83-py3-none-any.whl.metadata (9.8 kB)
Requirement already satisfied: new-reader>=0.1.7 in ./.local/lib/pypy3.9/site-packages (from umzz) (0.1.7)
Requirement already satisfied: threefive>=2.4.9 in ./.local/lib/pypy3.9/site-packages (from umzz) (2.4.9)
Collecting x9k3>=0.2.25 (from umzz)
  Obtaining dependency information for x9k3>=0.2.25 from https://files.pythonhosted.org/packages/e6/db/0438c79bf1f22200e63bb9d02a3cdb08216e7b6200e13d92419d89dd3cab/x9k3-0.2.25-py3-none-any.whl.metadata
  Using cached x9k3-0.2.25-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: pyaes in ./.local/lib/pypy3.9/site-packages (from m3ufu>=0.0.83->umzz) (1.6.1)
Using cached umzz-0.0.17-py3-none-any.whl (19 kB)
Using cached m3ufu-0.0.83-py3-none-any.whl (8.8 kB)
Using cached x9k3-0.2.25-py3-none-any.whl (13 kB)
Installing collected packages: m3ufu, x9k3, umzz
  Attempting uninstall: x9k3
    Found existing installation: x9k3 0.2.17
    Uninstalling x9k3-0.2.17:
      Successfully uninstalled x9k3-0.2.17
Successfully installed m3ufu-0.0.83 umzz-0.0.17 x9k3-0.2.25
```

maybe try it as a regular user?
What OS are you using?

**Comment by futzu** [comment]
https://github.com/futzu/umzz#writing-code

**Comment by futzu** [comment]
if you want to hire me, I can just do this for really quickly.

**Comment by futzu** [comment]
Sorry, I didn't see this before, what's happening?

**Comment by futzu** [comment]
Man you need more iframes, like mad. umzz is trying to cut 2 seconds segments, and the best it can do is 10.  That's a HUGE GOP size. FYI, a lot of the updates I've been doing on x9k3 are really for umzz. make sure you're using the latest x9k3.

**Comment by cooliobr** [comment]
sorry brother, I was on trip... I will try today
