### ISSUE TITLE
live option is not working

### ISSUE THREAD

**Issue by anuj998877** [futzu/umzz#11]
Hi Adrian, I have been trying this tool to generate abr stream and am not sure why it is not working
please let me know what I am doing wrong or the tool has any bug which I don;t see in output log.

Here are commands I am running:

`ffmpeg -re -i http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4 \
       -pix_fmt yuv420p \
       -reconnect 1 \
       -filter_complex "[0:v]split=3[v1][v2][v3];[v1]scale=480x270[v1out];[v2]scale=1280x720[v2out];[v3]scale=1920x1080[v3out]" \
       -map "[v1out]" -c:v:0 libx264 -preset faster -tune zerolatency -profile:v high -level 3.0 -b:v:0 800k -g 50 -r 25 \
       -map 0:a -c:a:0 aac -b:a:0 64k -ac 2 \
       -map "[v2out]" -c:v:1 libx264 -preset faster -tune zerolatency -profile:v high -level 3.0 -b:v:1 2000k -g 50 -r 25 \
       -map 0:a -c:a:1 aac -b:a:1 96k -ac 2 \
       -map "[v3out]" -c:v:2 libx264 -preset faster -tune zerolatency -profile:v high -level 3.0 -b:v:2 3500k -g 50 -r 25 \
       -map 0:a -c:a:2 aac -b:a:2 128k -ac 2 \
       -hls_time 6 \
       -hls_list_size 6 \
       -hls_allow_cache 0 \
       -hls_flags +delete_segments \
       -movflags +faststart \
       -var_stream_map "v:0,a:0 v:1,a:1 v:2,a:2" \
       -master_pl_name master.m3u8 \
       -f hls hls/%v/stream.m3u8`
       
       
       and then using umzz command like this
       ` umzz -i hls/master.m3u8 -s sidecar.txt -t 2 -w 7 -l -d -o umzz-op`
       
       I am not sure why it is not generating out even though the inputs are all correct.
       
       here is output of umzz for better understanding.
       
       `umzz -i hls/master.m3u8 -s sidecar.txt -t 2 -w 7 -l -d -o umzz-op 
Namespace(input='hls/master.m3u8', output_dir='umzz-op', sidecar_file='sidecar.txt', time=2.0, hls_tag='x_cue', window_size=7, delete=True, live=True, replay=False, shulga=False, version=False, program_date_time=False)
None
{
   "lines": [
      "#EXT-X-STREAM-INF:BANDWIDTH=950400,RESOLUTION=480x270,CODECS=\"avc1.64001e,mp4a.40.2\"",
      "0/stream.m3u8"
   ],
   "media": "hls/0/stream.m3u8",
   "tags": {
      "#EXT-X-STREAM-INF": {
         "CODECS": "avc1.64001e,mp4a.40.2",
         "RESOLUTION": "480x270",
         "BANDWIDTH": 950400
      }
   },
   "base_uri": "hls/",
   "relative_uri": "0/stream.m3u8"
}
None
{
   "lines": [
      "",
      "#EXT-X-STREAM-INF:BANDWIDTH=2305600,RESOLUTION=1280x720,CODECS=\"avc1.64001e,mp4a.40.2\"",
      "1/stream.m3u8"
   ],
   "media": "hls/1/stream.m3u8",
   "tags": {
      "#EXT-X-STREAM-INF": {
         "CODECS": "avc1.64001e,mp4a.40.2",
         "RESOLUTION": "1280x720",
         "BANDWIDTH": 2305600
      }
   },
   "base_uri": "hls/",
   "relative_uri": "1/stream.m3u8"
}
None
{
   "lines": [
      "",
      "#EXT-X-STREAM-INF:BANDWIDTH=3990800,RESOLUTION=1920x1080,CODECS=\"avc1.64001e,mp4a.40.2\"",
      "2/stream.m3u8"
   ],
   "media": "hls/2/stream.m3u8",
   "tags": {
      "#EXT-X-STREAM-INF": {
         "CODECS": "avc1.64001e,mp4a.40.2",
         "RESOLUTION": "1920x1080",
         "BANDWIDTH": 3990800
      }
   },
   "base_uri": "hls/",
   "relative_uri": "2/stream.m3u8"
}
{
  "headers": {
    "#EXTM3U": "",
    "#EXT-X-VERSION": 3
  }
}
BASE umzz-op
Process-1  is up
Process-2  is up
Process-3  is up
Process-1  is down
Process-3  is down
root@6511837e4ef8:/opt/casparcg# umzz -v
umzz 0.0.9
`

ls -R umzz-op/ :
0  1  2  master.m3u8

umzz-op/0:

umzz-op/1:

umzz-op/2:

**Comment by futzu** [comment]
I'm running that command with umzz2 and it's working  and playback is working.
let me know what happens.

**Comment by futzu** [comment]
Just grab the latest v0.0.13 , you can just run umzz  and it should work just fine.

**Comment by anuj998877** [comment]
Hey Adrian thanks for the feedback on ffmpeg command it really helped me gain more understanding of ffmpeg tool.

I ran the updated ffmpeg command and umzz one after another I see ffmpeg is still runing but umzz stopped after some time, unlike before now umzz produced abr chunks but for very short period of time.

here is output of umzz:
`umzz-op/2/seg16.ts:   start: 652.663222   end: 654.663222   duration: 2.000000
throttling 2.0
umzz-op/0/seg16.ts:   start: 652.823222   end: 654.823222   duration: 2.000000
throttling 2.0
umzz-op/1/seg17.ts:   start: 654.663222   end: 656.663222   duration: 0.192745
throttling 0.19
umzz-op/2/seg17.ts:   start: 654.663222   end: 656.663222   duration: 0.494600
throttling 0.49
umzz-op/0/seg17.ts:   start: 654.823222   end: 656.823222   duration: 0.125622
throttling 0.12
Process-1  is down
Process-3  is down
`
Please let me know if u need any other information for debug.

Thank you so much for your prompt response Adrian.

**Comment by futzu** [comment]
I screwed up on the ffmpeg command,  sorry man, I was distracted. :)

ffmpeg  -re -copyts  -i https://futzu.com/xaa.ts  \
 -g 30 -r 30 -flags +cgop \
-c:v libx264  -preset faster -tune zerolatency -profile:v high -level 3.0  \
-c:a aac \
-b:v:0 1000k -b:v:1 256k \
-filter:v:0 scale=1920:1080 -filter:v:1 scale=512:288 \           #   <-- you can scale like this
  -b:a:0 64k -b:a:1 32k \
-map 0:v -map 0:a -map 0:v -map 0:a \
-f hls -var_stream_map "v:0,a:0 v:1,a:1" \
-master_pl_name master.m3u8 \
fu3/mo_%v.m3u8

**Comment by futzu** [comment]
I am running your original  ffmpeg command  and the same umzz command, right now  and there is no problem.

What is it you're expecting `live` to do?
<br>
from your output, umzz ended  at 654 seconds aka 10minutes 54seconds

When I run ffprobe, it reports that video as 
```smalltalk
'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isomavc1mp42
    creation_time   : 2010-05-17T15:28:46.000000Z
  Duration: 00:10:53.80,    <----------------- 10 minutes 53.80 seconds
```
**it stopped because your video is complete.**

**Comment by anuj998877** [comment]
You are right for testing purpose I used that file but in real world problem I will be generating a livestream which will be live unless I end it manually my input source can be any live stream over udp.

Your utility seemed to work fine after latest ffmpeg command that u provided and I can see there is cpu throttling going on how can I optimise it ? and also how can we keep umzz process alive as I saw process 1 got down too early than other process.

My cloud cpu is very fast as my ffmpeg command run without any problem on it so wanted to understand how can I keep umzz process alive and minimise cpu throttling.

**Comment by futzu** [comment]
I can guide you through CPU optimization if you pay me, I got to eat too man. 
Try the latest version of umzz  v0.0.15 everything is working.

**Comment by futzu** [comment]
Encoding is a super expensive process, and you are creating  multiple streams, in realtime,  ffmpeg is going to use all the cpu available. umzz sleeps most of the time, spikes with it are when it wakes up and does something. Whenever you see "throttling 1.99 seconds" it's sleeping.

**Comment by futzu** [comment]
You really shouldn't be have cpu problems with umzz, here's what mine looks like with 3 renditions.

![image](https://github.com/futzu/umzz/assets/52701496/6df4d2d4-6f77-44d3-93db-4bdc1cc9c56b)

**Comment by anujchourange** [comment]
> Encoding is a super expensive process, and you are creating  multiple streams, in realtime,  ffmpeg is going to use all the cpu available. umzz sleeps most of the time, spikes with it are when it wakes up and does something. Whenever you see "throttling 1.99 seconds" it's sleeping.

Now I get it, Thanks a bunch!

**Comment by anujchourange** [comment]
> I can guide you through CPU optimization if you pay me, I got to eat too man. 
> Try the latest version of umzz  v0.0.15 everything is working.
> 

Thanks for the update! I'll check out umzz v0.0.15. I understand the need to eat – though I don't have big pockets I can definitely buy a coffee regardless of ur assistance as I find your opensource development very useful.
What's your preferred method of payment and communication for this?

**Comment by anuj998877** [comment]
Update:

I downgraded x9k3 to 0.2.19 version and it seems to add #EXT-X-CUE-OUT and CONTINUE headers in index.m3u8 files but there is a problem with chunk size/duration it is not consistent and exceeds the target duration, also the chunks during ad break were like 0.234 , 4.2424 seconds , and may be because of that the stream is not playing properly.

**Comment by anuj998877** [comment]
Update:

I downgraded x9k3 to 0.2.19 version and it seems to add #EXT-X-CUE-OUT and CONTINUE headers in index.m3u8 files but there is a problem with chunk size/duration it is not consistent and exceeds the target duration, also the chunks during ad break were like 0.234 , 4.2424 seconds , and may be because of that the stream is not playing properly.
<img width="1440" alt="Screenshot 2023-12-11 at 9 31 33 AM" src="https://github.com/futzu/umzz/assets/142009898/d8e51855-6963-4228-be36-a619f3b32159">

**Comment by cooliobr** [comment]
> Just a quick update Adrian,
> 
> I just tested the latest version and I don't see scte markers inside m3u8 files but on umzz logs I can see
> 
> `Cue from Sidecar: 9643.266667 /DAhAAAAAAAAAP/wEAUAAAAJf78A/gVdSoAACQAAAABAcfrx Cue from Sidecar: 9647.277333 /DAhAAAAAAAAAP/wEAUAAAAJf78A/gVdSoAACQAAAABAcfrx Cue from Sidecar: 9651.288 /DAhAAAAAAAAAP/wEAUAAAAJf78A/gVdSoAACQAAAABAcfrx Cue from Sidecar: 9655.341333 /DAhAAAAAAAAAP/wEAUAAAAJf78A/gVdSoAACQAAAABAcfrx `
> 
> here is my umzz command:
> 
> `nohup umzz -i /opt/master.m3u8 -s sidecar.txt -t 4 -w 10 -d -l -S -o /opt/hls/ssai > log/umzz_output_8DEC_07_44pm.log 2>&1 &`
> 
> sidecar.txt:
> 
> `0,/DAhAAAAAAAAAP/wEAUAAAAJf78A/gVdSoAACQAAAABAcfrx`

i faced same problem

**Comment by anuj998877** [comment]
> > Just a quick update Adrian,
> > I just tested the latest version and I don't see scte markers inside m3u8 files but on umzz logs I can see
> > `Cue from Sidecar: 9643.266667 /DAhAAAAAAAAAP/wEAUAAAAJf78A/gVdSoAACQAAAABAcfrx Cue from Sidecar: 9647.277333 /DAhAAAAAAAAAP/wEAUAAAAJf78A/gVdSoAACQAAAABAcfrx Cue from Sidecar: 9651.288 /DAhAAAAAAAAAP/wEAUAAAAJf78A/gVdSoAACQAAAABAcfrx Cue from Sidecar: 9655.341333 /DAhAAAAAAAAAP/wEAUAAAAJf78A/gVdSoAACQAAAABAcfrx `
> > here is my umzz command:
> > `nohup umzz -i /opt/master.m3u8 -s sidecar.txt -t 4 -w 10 -d -l -S -o /opt/hls/ssai > log/umzz_output_8DEC_07_44pm.log 2>&1 &`
> > sidecar.txt:
> > `0,/DAhAAAAAAAAAP/wEAUAAAAJf78A/gVdSoAACQAAAABAcfrx`
> 
> i faced same problem

I think the problem is with latest x9k3 version 
I have raised issue [here](https://github.com/futzu/x9k3/issues/29)

**Comment by anuj998877** [comment]
Bdw I ran umzz as well as x9k3 yesterday.

Today when I see the resource utilisation and I found the x9k3 (latest) process is using almost 20% of CPU usage and each UMZZ process was using 60% of CPU,  which was not the case at the beginning of starting these processess. 

Here is output of top :

```
Tasks:  22 total,   5 running,  17 sleeping,   0 stopped,   0 zombie
%Cpu(s): 91.4 us,  7.6 sy,  0.0 ni,  0.7 id,  0.0 wa,  0.0 hi,  0.3 si,  0.0 st
MiB Mem :  15689.2 total,   6787.8 free,   5496.7 used,   3404.6 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used.   9729.2 avail Mem 

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                   
  84452 root      20   0   27960  15556   4352 R  67.0   0.1 739:21.41 umzz                                                                           
  84450 root      20   0   32396  17752   4224 R  62.7   0.1 748:00.35 umzz                                                                           
  84451 root      20   0   29300  16320   4352 R  62.0   0.1 741:22.03 umzz                                                                           
  84159 root      20   0   33772  28156  10880 R  20.7   0.2  75:39.04 x9k3                                                                           
   5029 www-data  20   0   55852   4712   2816 S   0.7   0.0   3:16.13 nginx                                                                          
  84449 root      20   0   26404  18432   9088 S   0.3   0.1   1:05.01 umzz                                                                           
      1 root      20   0    4492   3456   3072 S   0.0   0.0   0:00.02 run_docker.sh                                                                  
   5028 root      20   0   55220   2280    640 S   0.0   0.0   0:00.00 nginx                                                                          
   5030 www-data  20   0   55852   4840   2944 S   0.0   0.0   0:01.70 nginx                                                                          
   5031 root      20   0    2888   1664   1664 S   0.0   0.0   0:00.00 run.sh                                                                         
   5032 www-data  20   0   55852   4584   2688 S   0.0   0.0   0:00.03 nginx                                                                          
   5033 www-data  20   0   55852   4456   2560 S   0.0   0.0   0:00.00 nginx                                                                           
   5081 root      20   0    5140   4096   3072 S   0.0   0.0   0:00.21 bash                                                                           
  11473 root      20   0   26604  17776   7936 S   0.0   0.1   0:25.84 python3                                                                          
 111697 root      20   0    7324   3328   2816 R   0.0   0.0   0:00.08 top  
 ```
 umzz recent log:
 
 ```
 /hls/ssai/0/seg16698.ts:   start: 67667.985956   end: 67671.985956   duration: 4.000000
throttling 0.1
/hls/ssai/1/seg16698.ts:   start: 67667.985956   end: 67671.985956   duration: 4.000000
throttling 0.07
/hls/ssai/2/seg16698.ts:   start: 67667.985956   end: 67671.985956   duration: 4.000000
throttling 0.06
/hls/ssai/0/seg16699.ts:   start: 67671.985956   end: 67675.985956   duration: 4.000000
throttling 0.09
/hls/ssai/2/seg16699.ts:   start: 67671.985956   end: 67675.985956   duration: 4.000000
throttling 0.06
/hls/ssai/1/seg16699.ts:   start: 67671.985956   end: 67675.985956   duration: 4.000000
throttling 0.07
```

**Comment by futzu** [comment]
What conclusion could I possibly draw from a top screen shot, and six lines from a log?
1. What options are you using?
2.  I need the stream. Without the stream, I can't help you. 
3. how about the whole log?

**Comment by futzu** [comment]
![image](https://github.com/futzu/umzz/assets/52701496/1c434b65-cad0-4cd4-a49f-cf6b44a1f044)

Where is your load average from top?

**Comment by futzu** [comment]
I've had it running for a couple hours and my CPU usages are below 5%, 
the only way I can see it growing is if you are doing VOD list for 12 hours, 
which I do not recommend.

**Comment by futzu** [comment]
I can tell you exactly why this is happening with umzz, because you downloading the video over a network, and I have stated emphatically that you cannot do it overr a network. Besides that, it's just plain stupid. You are download every   rendition at the same time.  Going forward, if you want my help, I need your command, stream, and logs. If you can't do that  I can't help you.

**Comment by anuj998877** [comment]
> I can tell you exactly why this is happening with umzz, because you downloading the video over a network, and I have stated emphatically that you cannot do it overr a network. Besides that, it's just plain stupid. You are download every rendition at the same time. Going forward, if you want my help, I need your command, stream, and logs. If you can't do that I can't help you.

No Adrian, I am not downloading video over network,
I am providing local hls stream.
here is my umzz command 
```
nohup umzz -i /hls/master.m3u8 -s sidecar.txt -t 4 -w 10 -d -l -S -o /hls/ssai > log/umzz_output_18DEC_07_44pm.log 2>&1 &
```

for reference here is my ffmpeg command to generate live hls stream

```
cd /hls
```
here using -g 50 because input stream is 25fps

```
nohup ffmpeg -re -i "udp://ip-address:9999?fifo_size=5000000&overrun_nonfatal=1" -map 0:v -map 0:a -filter:v:0 scale=1280x720 -c:v h264_nvenc -b:v:0 3M -g 50 -sc_threshold 0 -map 0:v -map 0:a -filter:v:1 scale=854x480 -c:v h264_nvenc -b:v:1 2M -g 50 -sc_threshold 0 -map 0:v -map 0:a -filter:v:2 scale=480x320 -c:v h264_nvenc -b:v:2 1M -g 50 -sc_threshold 0 -f hls -hls_time 4 -hls_list_size 10 -hls_flags delete_segments+append_list -hls_segment_type mpegts -master_pl_name master.m3u8 -var_stream_map v:0,a:0 v:1,a:1 v:2,a:2 -hls_segment_filename profile_%v/seg%03d.ts profile_%v/index.m3u8 &
```

**Comment by anuj998877** [comment]
> What conclusion could I possibly draw from a top screen shot, and six lines from a log?
> 
> 1. What options are you using?
here is my command:
```
nohup umzz -i /hls/master.m3u8 -s sidecar.txt -t 4 -w 10 -d -l -S -o /hls/ssai > log/umzz_output_18DEC_07_44pm.log 2>&1 &
```

> 2. I need the stream. Without the stream, I can't help you.

Which stream do you need Adrian the umzz output stream or input stream ? unfortunatly I am not running these scripts now but if u need it please let me know I will restart it and provide the details over email or direct message if prefered.

**Comment by anuj998877** [comment]
> how about the whole log?

attaching umzz log file to this message and screenshot of top command after spiking the cpu when running umzz process and without umzz process. Please check it.
Thanks
[umzz_output_19DEC_1249pm-cp.log](https://github.com/futzu/umzz/files/13732296/umzz_output_19DEC_1249pm-cp.log)

when umzz is running, note that the umzz was using less cpu (<5%) in first 2, 3 hours but then spiked.

<img width="967" alt="ss-19-1" src="https://github.com/futzu/umzz/assets/142009898/5cb639b7-a5cd-4f13-854b-98d42f5cf968">

after killing umzz processes

<img width="980" alt="ss-19-2" src="https://github.com/futzu/umzz/assets/142009898/ef941ccb-69de-4e42-9c23-033acfd863bf">
