### ISSUE TITLE
issue with sidecar file

### ISSUE THREAD

**Issue by cooliobr** [futzu/umzz#12]
´´ umzz -i /usr/share/ffplayout/public/live/playlist.m3u8 -o /usr/share/ffplayout/public/live/scte35-00 --sidecar_file /opt/mark/sidecar.txt -l -d -t 6 -p -n -T x_daterange -c  
Namespace(input='/usr/share/ffplayout/public/live/playlist.m3u8', continue_m3u8=True, delete=True, live=True, no_discontinuity=True, no_throttle=False, output_dir='/usr/share/ffplayout/public/live/scte35-00', program_date_time=True, replay=False, sidecar_file='/opt/mark/sidecar.txt', shulga=False, time=6.0, hls_tag='x_daterange', window_size=5, version=False)
None
{
   "lines": [
      "#EXT-X-STREAM-INF:BANDWIDTH=3550800,RESOLUTION=1280x720,CODECS=\"avc1.4d4029,mp4a.40.2\"",
      "stream_720p.m3u8"
   ],
   "media": "/usr/share/ffplayout/public/live/stream_720p.m3u8",
   "tags": {
      "#EXT-X-STREAM-INF": {
         "CODECS": "avc1.4d4029,mp4a.40.2",
         "RESOLUTION": "1280x720",
         "BANDWIDTH": 3550800
      }
   },
   "base_uri": "/usr/share/ffplayout/public/live/",
   "relative_uri": "stream_720p.m3u8"
}
None
{
   "lines": [
      "",
      "#EXT-X-STREAM-INF:BANDWIDTH=1570800,RESOLUTION=640x360,CODECS=\"avc1.4d4029,mp4a.40.2\"",
      "stream_360p.m3u8"
   ],
   "media": "/usr/share/ffplayout/public/live/stream_360p.m3u8",
   "tags": {
      "#EXT-X-STREAM-INF": {
         "CODECS": "avc1.4d4029,mp4a.40.2",
         "RESOLUTION": "640x360",
         "BANDWIDTH": 1570800
      }
   },
   "base_uri": "/usr/share/ffplayout/public/live/",
   "relative_uri": "stream_360p.m3u8"
}
{
  "headers": {
    "#EXTM3U": "",
    "#EXT-X-VERSION": 4
  }
}
BASE /usr/share/ffplayout/public/live/scte35-00
Rendition Process Started
Rendition Process Started
Process Process-1:
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/lib/pypy3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/local/lib/pypy3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/pypy3.10/site-packages/umzz.py", line 136, in mp_run
    x9mp = self.mk_x9mp(manifest, dir_name)
  File "/usr/local/lib/pypy3.10/site-packages/umzz.py", line 128, in mk_x9mp
    Path(x9mp.args.sidecar_file).touch()
  File "/usr/local/lib/pypy3.10/pathlib.py", line 1168, in touch
    self._accessor.touch(self, mode, exist_ok)
  File "/usr/local/lib/pypy3.10/pathlib.py", line 331, in touch
    fd = os.open(path, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: PosixPath('/usr/share/ffplayout/public/live/scte35-00/0/opt/mark/sidecar.txt')´´

**Comment by futzu** [comment]
I see what you're saying, give me a minute.

**Comment by futzu** [comment]
`python3 -mpip install --upgrade umzz `

and you should be good.

**Comment by futzu** [comment]
Hold on , I have a new update coming

**Comment by futzu** [comment]
this should be fixed.

**Comment by cooliobr** [comment]
thnks
