### ISSUE TITLE
i have one issue

### ISSUE THREAD

**Issue by cooliobr** [futzu/umzz#9]
I'm new to this concept, I'm testing umzz and I'm receiving only this message:
"umzz -i https://rbmn-live.akamaized.net/hls/live/590964/BoRB-AT/master.m3u8 -t 3 -p -s sidecar.txt -o ./1/
Namespace(delete=False, hls_tag='x_cue', input='https://rbmn-live.akamaized.net/hls/live/590964/BoRB-AT/master.m3u8', output_dir='./1/', program_date_time=True, replay=False, shulga=False, sidecar_file='sidecar.txt', time=3.0, version=False, window_size=5)"

Am I forgetting to do something? If anyone has any information

**Comment by futzu** [comment]
Sorry , I thought I had answered this already, that's just debug info, not an error. 
umzz will not work correctly over a network, it's like trying to play all the renditions at the same time.
umzz needs to run on the same server as the master.m3u8 it's parsing

**Comment by cooliobr** [comment]
Ok, thanks brother


Att.

Rafael Machado
*HALLO! Midia Group.*




Em ter., 18 de jul. de 2023 às 00:13, Adrian ***@***.***>
escreveu:

**Comment by cooliobr** [comment]
> Sorry , I thought I had answered this already, that's just debug info, not an error.
> umzz will not work correctly over a network, it's like trying to play all the renditions at the same time.
> umzz needs to run on the same server as the master.m3u8 it's parsing

I receive same output...

umzz -i playlist.m3u8 -o /home/playout/live/ --live -s /home/playout/sidecar.txt 
Namespace(delete=False, hls_tag='x_cue', input='playlist.m3u8', live=True, output_dir='/home/playout/live/', program_date_time=False, replay=False, shulga=False, sidecar_file='/home/playout/sidecar.txt', time=2, version=False, window_size=5)
playout@Hallo-Leo-e-Lully-192-168-234-53:/usr/share/ffplayout/public/live/ch6$ 

How can I find where I am wrong as I have tried in all possible ways
